use std::collections::BTreeSet;

use chrono::{DateTime, Utc};
use paste_domain::{
    CaptureFlags, CapturedItem, CapturedRepresentation, DeviceMetadata, RepresentationKind,
    SourceApplication,
};
use thiserror::Error;

pub const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
pub const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
pub const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";
pub const INTERNAL_PASTEBOARD_TYPE: &str = "io.pasters.internal.clip";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CaptureLimits {
    pub max_items: usize,
    pub max_representations_per_item: usize,
    pub max_representation_bytes: usize,
    pub max_total_bytes: usize,
}

impl Default for CaptureLimits {
    fn default() -> Self {
        Self {
            max_items: 64,
            max_representations_per_item: 32,
            max_representation_bytes: 64 * 1024 * 1024,
            max_total_bytes: 256 * 1024 * 1024,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClipboardPrivacyPolicy {
    excluded_bundle_ids: BTreeSet<String>,
    pub ignore_confidential: bool,
    pub ignore_transient: bool,
    pub ignore_auto_generated: bool,
}

impl Default for ClipboardPrivacyPolicy {
    fn default() -> Self {
        Self::secure_default()
    }
}

impl ClipboardPrivacyPolicy {
    #[must_use]
    pub fn secure_default() -> Self {
        Self {
            excluded_bundle_ids: BTreeSet::new(),
            ignore_confidential: true,
            ignore_transient: true,
            ignore_auto_generated: false,
        }
    }

    pub fn exclude_bundle_id(&mut self, bundle_id: impl Into<String>) {
        self.excluded_bundle_ids
            .insert(bundle_id.into().to_ascii_lowercase());
    }

    pub fn include_bundle_id(&mut self, bundle_id: &str) {
        self.excluded_bundle_ids
            .remove(&bundle_id.to_ascii_lowercase());
    }

    #[must_use]
    pub fn evaluate(&self, descriptor: &PasteboardDescriptor) -> Option<IgnoreReason> {
        if self
            .excluded_bundle_ids
            .contains(&descriptor.source.bundle_identifier.to_ascii_lowercase())
        {
            return Some(IgnoreReason::ExcludedApplication);
        }

        let has_type = |needle: &str| {
            descriptor
                .item_types
                .iter()
                .flatten()
                .any(|value| value == needle)
        };
        if self.ignore_confidential && has_type(CONCEALED_TYPE) {
            Some(IgnoreReason::Confidential)
        } else if self.ignore_transient && has_type(TRANSIENT_TYPE) {
            Some(IgnoreReason::Transient)
        } else if has_type(INTERNAL_PASTEBOARD_TYPE) {
            Some(IgnoreReason::ApplicationGenerated)
        } else if self.ignore_auto_generated && has_type(AUTO_GENERATED_TYPE) {
            Some(IgnoreReason::AutoGenerated)
        } else {
            None
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PasteboardDescriptor {
    pub change_count: i64,
    pub source: SourceApplication,
    pub item_types: Vec<Vec<String>>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IgnoreReason {
    ExcludedApplication,
    Confidential,
    Transient,
    AutoGenerated,
    ApplicationGenerated,
    Empty,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawPasteboardRepresentation {
    pub uti: String,
    pub bytes: Vec<u8>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawPasteboardItem {
    pub representations: Vec<RawPasteboardRepresentation>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawPasteboardSnapshot {
    pub descriptor: PasteboardDescriptor,
    pub items: Vec<RawPasteboardItem>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ClipboardPoll {
    Unchanged,
    Ignored {
        change_count: i64,
        reason: IgnoreReason,
    },
    Captured {
        change_count: i64,
        items: Vec<CapturedItem>,
    },
}

pub trait ClipboardSource {
    /// Advance past the current generation without obtaining its contents.
    /// On success only a subsequent change is eligible for capture. Resume
    /// must remain paused on failure; implementations must not default to a
    /// payload read or a no-op that can replay a paused generation.
    fn discard_current(&mut self) -> Result<(), ClipboardError>;

    fn poll(
        &mut self,
        policy: &ClipboardPrivacyPolicy,
        limits: CaptureLimits,
        device: &DeviceMetadata,
    ) -> Result<ClipboardPoll, ClipboardError>;
}

pub fn captures_from_raw(
    snapshot: RawPasteboardSnapshot,
    policy: &ClipboardPrivacyPolicy,
    limits: CaptureLimits,
    device: &DeviceMetadata,
    captured_at: DateTime<Utc>,
) -> Result<ClipboardPoll, ClipboardError> {
    if let Some(reason) = policy.evaluate(&snapshot.descriptor) {
        return Ok(ClipboardPoll::Ignored {
            change_count: snapshot.descriptor.change_count,
            reason,
        });
    }
    if snapshot.items.len() > limits.max_items {
        return Err(ClipboardError::TooManyItems {
            actual: snapshot.items.len(),
            limit: limits.max_items,
        });
    }

    let mut total_bytes = 0_usize;
    let mut captures = Vec::with_capacity(snapshot.items.len());
    for item in snapshot.items {
        if item.representations.len() > limits.max_representations_per_item {
            return Err(ClipboardError::TooManyRepresentations {
                actual: item.representations.len(),
                limit: limits.max_representations_per_item,
            });
        }

        let mut representations = Vec::with_capacity(item.representations.len());
        for raw in item.representations {
            if is_policy_marker(&raw.uti) || raw.bytes.is_empty() {
                continue;
            }
            if raw.bytes.len() > limits.max_representation_bytes {
                return Err(ClipboardError::RepresentationTooLarge {
                    uti: raw.uti,
                    actual: raw.bytes.len(),
                    limit: limits.max_representation_bytes,
                });
            }
            total_bytes = total_bytes
                .checked_add(raw.bytes.len())
                .ok_or(ClipboardError::SizeOverflow)?;
            if total_bytes > limits.max_total_bytes {
                return Err(ClipboardError::SnapshotTooLarge {
                    actual: total_bytes,
                    limit: limits.max_total_bytes,
                });
            }

            let kind = representation_kind(&raw.uti);
            if !paste_domain::valid_native_type(&raw.uti) {
                return Err(ClipboardError::InvalidNativeType);
            }
            representations.push(CapturedRepresentation {
                mime_type: mime_type(&kind, &raw.uti),
                native_type: Some(raw.uti),
                file_name: None,
                kind,
                bytes: raw.bytes,
            });
        }
        if representations.is_empty() {
            continue;
        }
        captures.push(CapturedItem {
            captured_at,
            source: snapshot.descriptor.source.clone(),
            device: device.clone(),
            flags: CaptureFlags::default(),
            representations,
        });
    }

    if captures.is_empty() {
        Ok(ClipboardPoll::Ignored {
            change_count: snapshot.descriptor.change_count,
            reason: IgnoreReason::Empty,
        })
    } else {
        Ok(ClipboardPoll::Captured {
            change_count: snapshot.descriptor.change_count,
            items: captures,
        })
    }
}

#[must_use]
pub fn representation_kind(uti: &str) -> RepresentationKind {
    match uti {
        "public.utf8-plain-text"
        | "public.utf16-external-plain-text"
        | "public.plain-text"
        | "NSStringPboardType" => RepresentationKind::PlainText,
        "public.html" | "Apple HTML pasteboard type" => RepresentationKind::Html,
        "public.rtf" | "NeXT Rich Text Format v1.0 pasteboard type" => RepresentationKind::Rtf,
        "public.url" => RepresentationKind::Url,
        "public.url-name" => RepresentationKind::PlainText,
        "public.png" => RepresentationKind::Png,
        "public.tiff" => RepresentationKind::Tiff,
        "com.adobe.pdf" => RepresentationKind::Pdf,
        "public.file-url" | "NSFilenamesPboardType" => RepresentationKind::FileUrls,
        "com.apple.cocoa.pasteboard.color" | "public.color" => RepresentationKind::Color,
        custom => RepresentationKind::Custom(custom.into()),
    }
}

fn mime_type(kind: &RepresentationKind, native_type: &str) -> Option<String> {
    match kind {
        RepresentationKind::PlainText if native_type == "public.utf16-external-plain-text" => {
            Some("text/plain; charset=utf-16".into())
        }
        RepresentationKind::PlainText => Some("text/plain; charset=utf-8".into()),
        RepresentationKind::Html => Some("text/html; charset=utf-8".into()),
        RepresentationKind::Rtf => Some("text/rtf".into()),
        RepresentationKind::Url => Some("text/uri-list".into()),
        RepresentationKind::Png => Some("image/png".into()),
        RepresentationKind::Tiff => Some("image/tiff".into()),
        RepresentationKind::Pdf => Some("application/pdf".into()),
        RepresentationKind::FileUrls
        | RepresentationKind::Color
        | RepresentationKind::Custom(_) => None,
    }
}

fn is_policy_marker(uti: &str) -> bool {
    matches!(uti, CONCEALED_TYPE | TRANSIENT_TYPE | AUTO_GENERATED_TYPE)
}

#[derive(Debug, Error, Eq, PartialEq)]
pub enum ClipboardError {
    #[error("pasteboard contains {actual} items, limit is {limit}")]
    TooManyItems { actual: usize, limit: usize },
    #[error("pasteboard item contains {actual} representations, limit is {limit}")]
    TooManyRepresentations { actual: usize, limit: usize },
    #[error("pasteboard representation {uti} is {actual} bytes, limit is {limit}")]
    RepresentationTooLarge {
        uti: String,
        actual: usize,
        limit: usize,
    },
    #[error("pasteboard snapshot is {actual} bytes, limit is {limit}")]
    SnapshotTooLarge { actual: usize, limit: usize },
    #[error("pasteboard size overflow")]
    SizeOverflow,
    #[error("pasteboard is unavailable")]
    Unavailable,
    #[error("pasteboard changed while reading; snapshot discarded")]
    ChangedDuringRead,
    #[error("clipboard item has no textual representation")]
    NoTextualRepresentation,
    #[error("failed to write pasteboard representation {uti}")]
    WriteFailed { uti: String },
    #[error("paste target state lock was poisoned")]
    PasteTargetPoisoned,
    #[error("automatic paste must advance on the AppKit main thread")]
    PasteRequiresMainThread,
    #[error("automatic paste context changed before event delivery")]
    PasteContextChanged,
    #[error("native pasteboard type is invalid")]
    InvalidNativeType,
    #[error("multiple representations claim the same native pasteboard type")]
    DuplicateNativeType,
    #[error("旧记录没有足够的原生格式信息，无法安全还原该表示；仍可使用文件拖出。")]
    AmbiguousLegacyRepresentation,
    #[error("could not create a macOS keyboard event source")]
    EventSourceUnavailable,
    #[error("could not create a macOS paste keyboard event")]
    EventCreationFailed,
}
